[General]
plugin_priority=itemimage, itemencrypted, itemfakevim, itemnotes, itemsync, itemtags, itemtext

[Options]
action_has_input=false
action_has_output=false
action_output_tab=
action_separator=\\n
activate_closes=true
activate_focuses=true
activate_pastes=true
always_on_top=true
autostart=false
check_clipboard=true
check_selection=false
clipboard_notification_lines=0
clipboard_tab=&clipboard
close_on_unfocus=true
command_history_size=100
confirm_exit=false
copy_clipboard=false
copy_selection=false
disable_tray=false
expire_tab=0
hide_main_window=true
hide_main_window_in_task_bar=true
hide_tabs=false
item_popup_interval=0
max_items=1000
move=true
open_windows_on_current_screen=true
save_delay_ms_on_item_added=300
save_filter_history=false
show_simple_items=false
show_tab_item_count=true
tab_tree=false
tabs=&clipboard, &Pinned
text_wrap=true
transparency=0
transparency_focused=0
tray_commands=true
tray_images=true
tray_item_paste=true
tray_items=5
tray_tab=
tray_tab_is_current=true
vi=false
window_key_press_time=100

[Theme]
theme=noctalia.ini
