color0 #082649
color1 #fd4663
color2 #76b4fc
color3 #7b76fc
color4 #be76fc
color5 #82bbfc
color6 #8782fc
color7 #f2f2f3
color8 #616870
color9 #fd4663
color10 #76b4fc
color11 #7b76fc
color12 #be76fc
color13 #82bbfc
color14 #8782fc
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #031d3a
background            #031d3a
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #082649
active_border_color   #76b4fc
inactive_border_color #082649
url_color             #76b4fc

active_tab_foreground   #181e25
active_tab_background   #76b4fc
inactive_tab_foreground #afb2b6
inactive_tab_background #082649
cursor_trail_color      #afb2b6
