color0 #1c2c36
color1 #fd4663
color2 #67b8e4
color3 #6a7ee8
color4 #9673da
color5 #93ccec
color6 #96a2e9
color7 #f2f2f3
color8 #616b70
color9 #fd4663
color10 #67b8e4
color11 #6a7ee8
color12 #9673da
color13 #93ccec
color14 #96a2e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #152128
background            #152128
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #1c2c36
active_border_color   #67b8e4
inactive_border_color #1c2c36
url_color             #67b8e4

active_tab_foreground   #182025
active_tab_background   #67b8e4
inactive_tab_foreground #afb4b6
inactive_tab_background #1c2c36
cursor_trail_color      #afb4b6
