#!/usr/bin/env bash

detect_machine() {
    info "Detecting machine..."

    ARCH="$(uname -m)"
    HOSTNAME="$(hostname)"
    USERNAME="$(id -un)"
    USER_HOME="${DOTFILES_USER_HOME:-$HOME}"

    if [ -z "${DOTFILES_USER_HOME:-}" ] && [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
        USERNAME="$SUDO_USER"
        USER_HOME="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
    fi

    case "$ARCH" in
        x86_64)
            SYSTEM="x86_64-linux"
            ;;
        *)
            error "Unsupported architecture: $ARCH"
            ;;
    esac

    echo "  Repository : $REPO_ROOT"
    echo "  System     : $SYSTEM"
    echo "  Hostname   : $HOSTNAME"
    echo "  User       : $USERNAME"
    echo "  Home       : $USER_HOME"

    success "Machine detected"
}

prepare_machine_dir() {
    MACHINE_DIR="${DOTFILES_MACHINE_DIR:-$REPO_ROOT/.machine}"
    mkdir -p "$MACHINE_DIR"
}

generate_machine_state() {
    info "Generating hardware configuration..."

    HARDWARE_CONFIG="$MACHINE_DIR/hardware-configuration.nix"
    # Keep the generated file owned by the invoking user; only hardware probing needs root.
    # shellcheck disable=SC2024
    sudo nixos-generate-config --show-hardware-config > "$HARDWARE_CONFIG"
    success "Hardware configuration generated"

    info "Generating machine configuration..."
    MACHINE_CONFIG="$MACHINE_DIR/configuration.nix"
    cat > "$MACHINE_CONFIG" <<EOF
# ============================================================
# AUTO-GENERATED MACHINE CONFIGURATION
#
# Generated by:
#   scripts/bootstrap
#
# DO NOT EDIT MANUALLY.
# This file is machine-specific and should NOT be committed.
# ============================================================

{
  imports = [
    ../configuration.nix
    ./hardware-configuration.nix
    ./hardware-extra.nix
  ];

  networking.hostName = "$HOSTNAME";
  dotfiles.primaryUser = "$USERNAME";

  # Machine-local boot and state compatibility policy.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  system.stateVersion = "${DOTFILES_STATE_VERSION:-26.05}";

  users.users."$USERNAME" = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "networkmanager"
      "input"
      "uinput"
      "docker"
      "seat"
      "video"
    ];
  };
}
EOF
    success "Machine configuration generated"

    HARDWARE_EXTRA="$MACHINE_DIR/hardware-extra.nix"
    if [ ! -f "$HARDWARE_EXTRA" ]; then
        cat > "$HARDWARE_EXTRA" <<'EOF'
# Machine-local hardware opt-ins. Add imports only for hardware present here.
{
  imports = [
    # ../modules/hardware/intel-graphics.nix
    # ../modules/hardware/weikav-nut75.nix
  ];

  # Optional machine-specific kernel parameters.
  # boot.kernelParams = [
  #   "usbcore.autosuspend=-1"
  #   "hid_apple.fnmode=0"
  # ];
}
EOF
        success "Machine hardware opt-in template generated"
    fi
}

ensure_gitignore() {
    GITIGNORE="${DOTFILES_GITIGNORE:-$REPO_ROOT/.gitignore}"

    if [ ! -f "$GITIGNORE" ]; then
        touch "$GITIGNORE"
    fi

    if ! grep -qxF ".machine/" "$GITIGNORE"; then
        echo ".machine/" >> "$GITIGNORE"
    fi

    success ".machine/ added to .gitignore"
}

show_generated_state() {
    info "Generated configuration:"
    echo
    cat "$MACHINE_CONFIG"
    echo
}
