#!/usr/bin/env bash

set -euo pipefail

info() {
    echo
    echo "==> $1"
}

success() {
    echo "✓ $1"
}

error() {
    echo "✗ $1" >&2
    exit 1
}

warn() {
    echo "! $1"
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_ROOT"


# ------------------------------------------------------------
# Basic checks
# ------------------------------------------------------------

info "Checking environment..."

command -v nix >/dev/null 2>&1 \
    || error "Nix is not installed."

command -v nixos-generate-config >/dev/null 2>&1 \
    || error "nixos-generate-config is not available."

command -v sudo >/dev/null 2>&1 \
    || error "sudo is not installed."

success "Environment OK"


# ------------------------------------------------------------
# Detect machine information
# ------------------------------------------------------------

info "Detecting machine..."

ARCH="$(uname -m)"
HOSTNAME="$(hostname)"
USERNAME="$(id -un)"
USER_HOME="$HOME"

if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    USERNAME="$SUDO_USER"
    USER_HOME="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
fi

case "$ARCH" in
    x86_64)
        SYSTEM="x86_64-linux"
        ;;

    aarch64)
        SYSTEM="aarch64-linux"
        ;;

    *)
        error "Unsupported architecture: $ARCH"
        ;;
esac

echo "  Repository : $REPO_ROOT"
echo "  System     : $SYSTEM"
echo "  Hostname   : $HOSTNAME"
echo "  User       : $USERNAME"
echo "  Home       : $USER_HOME"

success "Machine detected"


# ------------------------------------------------------------
# Local machine directory
# ------------------------------------------------------------

MACHINE_DIR="$REPO_ROOT/.machine"

mkdir -p "$MACHINE_DIR"


# ------------------------------------------------------------
# Generate hardware configuration
# ------------------------------------------------------------

info "Generating hardware configuration..."

HARDWARE_CONFIG="$MACHINE_DIR/hardware-configuration.nix"

# Keep the generated file owned by the invoking user; only hardware probing needs root.
# shellcheck disable=SC2024
sudo nixos-generate-config --show-hardware-config > "$HARDWARE_CONFIG"

success "Hardware configuration generated"


# ------------------------------------------------------------
# Generate machine configuration
# ------------------------------------------------------------

info "Generating machine configuration..."

MACHINE_CONFIG="$MACHINE_DIR/configuration.nix"

cat > "$MACHINE_CONFIG" <<EOF
# ============================================================
# AUTO-GENERATED MACHINE CONFIGURATION
#
# Generated by:
#   scripts/bootstrap
#
# DO NOT EDIT MANUALLY.
# This file is machine-specific and should NOT be committed.
# ============================================================

{
  imports = [
    ../configuration.nix
    ./hardware-configuration.nix
  ];

  # ----------------------------------------------------------
  # Machine
  # ----------------------------------------------------------

  networking.hostName = "$HOSTNAME";

  # ----------------------------------------------------------
  # User
  # ----------------------------------------------------------

  users.users."$USERNAME" = {
    isNormalUser = true;

    extraGroups = [
      "wheel"
      "networkmanager"
      "input"
      "uinput"
      "docker"
    ];
  };
}
EOF

success "Machine configuration generated"


# ------------------------------------------------------------
# Make sure .machine is ignored
# ------------------------------------------------------------

GITIGNORE="$REPO_ROOT/.gitignore"

if [ ! -f "$GITIGNORE" ]; then
    touch "$GITIGNORE"
fi

if ! grep -qxF ".machine/" "$GITIGNORE"; then
    echo ".machine/" >> "$GITIGNORE"
fi

success ".machine/ added to .gitignore"


# ------------------------------------------------------------
# Show generated configuration
# ------------------------------------------------------------

info "Generated configuration:"

echo
cat "$MACHINE_CONFIG"
echo


# ------------------------------------------------------------
# Setup wallpapers
# ------------------------------------------------------------

info "Checking wallpapers..."

WALLPAPER_SRC="$REPO_ROOT/resources/static/wallpapers"
WALLPAPER_DEST="$USER_HOME/Pictures/Wallpapers"

if [ -e "$WALLPAPER_DEST" ]; then
    info "Pictures/Wallpapers already exists at $WALLPAPER_DEST, skipping copy."
else
    if [ -d "$WALLPAPER_SRC" ]; then
        info "Copying wallpapers to $WALLPAPER_DEST..."
        mkdir -p "$USER_HOME/Pictures" "$USER_HOME/Videos" "$USER_HOME/Downloads" "$USER_HOME/Documents"
        cp -r "$WALLPAPER_SRC" "$WALLPAPER_DEST"
        if [ -n "${SUDO_USER:-}" ]; then
            chown -R "$SUDO_USER:" "$USER_HOME/Pictures" "$USER_HOME/Videos" "$USER_HOME/Downloads" "$USER_HOME/Documents" 2>/dev/null || true
        fi
        success "Wallpapers copied successfully to $WALLPAPER_DEST"
    else
        echo "! Wallpaper source directory not found at $WALLPAPER_SRC"
    fi
fi


# ------------------------------------------------------------
# Setup dotfiles symlinks (~/.config)
# ------------------------------------------------------------

info "Linking configuration files to $USER_HOME/.config..."

safe_link() {
    local src="$1"
    local dest="$2"
    if [ -e "$dest" ] && [ ! -L "$dest" ]; then
        local backup
        backup="${dest}.pre-dotfiles.$(date +%Y%m%d%H%M%S)"
        mv -- "$dest" "$backup"
        warn "Moved existing $dest to $backup"
    fi
    ln -sfn "$src" "$dest"
}

mkdir -p "$USER_HOME/.config"
mkdir -p "$USER_HOME/.config/noctalia"
mkdir -p "$USER_HOME/.config/fcitx5"

# Niri configuration
safe_link "$REPO_ROOT/resources/niri" "$USER_HOME/.config/niri"

# Noctalia configuration (paths use ~ so the tracked file stays portable)
safe_link "$REPO_ROOT/resources/noctalia/config.toml" "$USER_HOME/.config/noctalia/config.toml"

# Kitty configuration
safe_link "$REPO_ROOT/resources/kitty" "$USER_HOME/.config/kitty"

# Antigravity IDE custom configuration & CSS
safe_link "$REPO_ROOT/resources/antigravity" "$USER_HOME/.config/antigravity"

# Starship prompt configuration
if [ -f "$REPO_ROOT/resources/starship/starship.toml" ]; then
    safe_link "$REPO_ROOT/resources/starship/starship.toml" "$USER_HOME/.config/starship.toml"
fi

# Zsh & Zimfw shell configuration
if [ -d "$REPO_ROOT/resources/zsh" ]; then
    safe_link "$REPO_ROOT/resources/zsh/.zshrc" "$USER_HOME/.zshrc"
    safe_link "$REPO_ROOT/resources/zsh/.zimrc" "$USER_HOME/.zimrc"
fi

# Zellij terminal multiplexer configuration
if [ -d "$REPO_ROOT/resources/zellij" ]; then
    safe_link "$REPO_ROOT/resources/zellij" "$USER_HOME/.config/zellij"
fi

# Neovim configuration
if [ -d "$REPO_ROOT/resources/nvim" ]; then
    safe_link "$REPO_ROOT/resources/nvim" "$USER_HOME/.config/nvim"
fi

# Fcitx5 Vietnamese input method configuration
if [ -d "$REPO_ROOT/resources/fcitx5" ]; then
    safe_link "$REPO_ROOT/resources/fcitx5/config" "$USER_HOME/.config/fcitx5/config"
    safe_link "$REPO_ROOT/resources/fcitx5/profile" "$USER_HOME/.config/fcitx5/profile"
    mkdir -p "$USER_HOME/.config/fcitx5/conf"
    if [ -d "$REPO_ROOT/resources/fcitx5/conf" ]; then
        safe_link "$REPO_ROOT/resources/fcitx5/conf/bamboo.conf" "$USER_HOME/.config/fcitx5/conf/bamboo.conf"
        safe_link "$REPO_ROOT/resources/fcitx5/conf/classicui.conf" "$USER_HOME/.config/fcitx5/conf/classicui.conf"
    fi
fi

# Git global configuration
if [ -f "$REPO_ROOT/resources/git/.gitconfig" ]; then
    safe_link "$REPO_ROOT/resources/git/.gitconfig" "$USER_HOME/.gitconfig"
fi
if [ -f "$REPO_ROOT/resources/git/.gitconfig-1bitlab" ]; then
    safe_link "$REPO_ROOT/resources/git/.gitconfig-1bitlab" "$USER_HOME/.gitconfig-1bitlab"
fi

# SSH client configuration
if [ -f "$REPO_ROOT/resources/ssh/config" ]; then
    mkdir -p "$USER_HOME/.ssh"
    chmod 700 "$USER_HOME/.ssh"
    safe_link "$REPO_ROOT/resources/ssh/config" "$USER_HOME/.ssh/config"
fi

# Fastfetch system info configuration
if [ -d "$REPO_ROOT/resources/fastfetch" ]; then
    mkdir -p "$USER_HOME/.config/fastfetch"
    if [ ! -f "$USER_HOME/.config/fastfetch/config.jsonc" ] || [ -L "$USER_HOME/.config/fastfetch/config.jsonc" ]; then
        rm -f "$USER_HOME/.config/fastfetch/config.jsonc"
        cp "$REPO_ROOT/resources/fastfetch/config.jsonc" "$USER_HOME/.config/fastfetch/config.jsonc"
        success "Copied fastfetch configuration template"
    fi
fi

# Yazi modern file manager configuration
if [ -d "$REPO_ROOT/resources/yazi" ]; then
    mkdir -p "$USER_HOME/.config/yazi"
    safe_link "$REPO_ROOT/resources/yazi/keymap.toml" "$USER_HOME/.config/yazi/keymap.toml"
    safe_link "$REPO_ROOT/resources/yazi/yazi.toml" "$USER_HOME/.config/yazi/yazi.toml"
fi

# Custom application desktop entries (Jira, etc.)
mkdir -p "$USER_HOME/.local/share/applications"
if [ -f "$REPO_ROOT/resources/static/jira.desktop" ]; then
    safe_link "$REPO_ROOT/resources/static/jira.desktop" "$USER_HOME/.local/share/applications/jira.desktop"
fi
if [ -f "$REPO_ROOT/resources/static/jira.svg" ]; then
    mkdir -p "$USER_HOME/.local/share/icons/hicolor/scalable/apps"
    safe_link "$REPO_ROOT/resources/static/jira.svg" "$USER_HOME/.local/share/icons/hicolor/scalable/apps/jira.svg"
fi

# Systemd user services (e.g. 9router autostart)
if [ -d "$REPO_ROOT/resources/systemd/user" ]; then
    mkdir -p "$USER_HOME/.config/systemd/user"
    for srv in "$REPO_ROOT/resources/systemd/user/"*.service; do
        if [ -f "$srv" ]; then
            safe_link "$srv" "$USER_HOME/.config/systemd/user/$(basename "$srv")"
        fi
    done
fi

# Link workflow utilities to ~/.local/bin (accessible system-wide via PATH)
mkdir -p "$USER_HOME/.local/bin"
safe_link "$REPO_ROOT/scripts/pj.sh" "$USER_HOME/.local/bin/pj"
safe_link "$REPO_ROOT/scripts/flakify.sh" "$USER_HOME/.local/bin/flakify"
safe_link "$REPO_ROOT/scripts/vault.sh" "$USER_HOME/.local/bin/vault"
safe_link "$REPO_ROOT/scripts/secrets.sh" "$USER_HOME/.local/bin/secrets"
safe_link "$REPO_ROOT/scripts/jira-app.sh" "$USER_HOME/.local/bin/jira-app"
safe_link "$REPO_ROOT/scripts/build.sh" "$USER_HOME/.local/bin/rebuild"
safe_link "$REPO_ROOT/scripts/sync-noctalia.sh" "$USER_HOME/.local/bin/sync-theme"
safe_link "$REPO_ROOT/scripts/screenshot.sh" "$USER_HOME/.local/bin/screenshot"
safe_link "$REPO_ROOT/scripts/doctor.sh" "$USER_HOME/.local/bin/doctor"
safe_link "$REPO_ROOT/scripts/check.sh" "$USER_HOME/.local/bin/dotfiles-check"
safe_link "$REPO_ROOT/scripts/tunnel.sh" "$USER_HOME/.local/bin/tunnel"
safe_link "$REPO_ROOT/scripts/cleanup.sh" "$USER_HOME/.local/bin/cleanup"
safe_link "$REPO_ROOT/scripts/init-9router.sh" "$USER_HOME/.local/bin/init-9router"
safe_link "$REPO_ROOT/scripts/init-9router.sh" "$USER_HOME/.local/bin/9router-init"
safe_link "$REPO_ROOT/scripts/init-omniroute.sh" "$USER_HOME/.local/bin/init-omniroute"
safe_link "$REPO_ROOT/scripts/sync-omniroute.sh" "$USER_HOME/.local/bin/sync-omniroute"
safe_link "$REPO_ROOT/scripts/reconcile-ai-gateways.sh" "$USER_HOME/.local/bin/reconcile-ai-gateways"

# Configure user-level npm global prefix to prevent writing into read-only /nix/store
if command -v npm >/dev/null 2>&1; then
    if [ -n "${SUDO_USER:-}" ]; then
        sudo -u "$SUDO_USER" npm config set prefix "$USER_HOME/.local" 2>/dev/null || true
    else
        npm config set prefix "$USER_HOME/.local" 2>/dev/null || true
    fi
fi

if [ -n "${SUDO_USER:-}" ]; then
    chown -h "$SUDO_USER:" "$USER_HOME/.config/niri" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.config/noctalia/config.toml" 2>/dev/null || true
    chown -R "$SUDO_USER:" "$USER_HOME/.config/noctalia" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.config/kitty" 2>/dev/null || true
    chown -R "$SUDO_USER:" "$USER_HOME/.config/kitty" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.config/antigravity" 2>/dev/null || true
    chown -R "$SUDO_USER:" "$USER_HOME/.config/antigravity" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.config/nvim" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.config/zellij" 2>/dev/null || true
    chown -R "$SUDO_USER:" "$USER_HOME/.config/yazi" 2>/dev/null || true
    chown -R "$SUDO_USER:" "$USER_HOME/.local/bin" 2>/dev/null || true
    chown -R "$SUDO_USER:" "$USER_HOME/.local/lib/node_modules" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.config/starship.toml" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.zshrc" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.config/fcitx5/config" 2>/dev/null || true
    chown -h "$SUDO_USER:" "$USER_HOME/.config/fcitx5/profile" 2>/dev/null || true
    chown -R "$SUDO_USER:" "$USER_HOME/.config" 2>/dev/null || true
fi

success "Configuration files linked successfully!"


# ------------------------------------------------------------
# Build
# ------------------------------------------------------------

info "Building NixOS..."

sudo nixos-rebuild switch \
    -I "nixos-config=$MACHINE_CONFIG"

success "NixOS configuration applied successfully!"

info "Synchronizing editor configuration and extensions..."
"$REPO_ROOT/scripts/sync-editors.sh"

# ------------------------------------------------------------
# AI Gateways Reconciliation (9Router & OmniRoute)
# ------------------------------------------------------------
info "Reconciling AI Gateways (9Router & OmniRoute)..."

if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    sudo -u "$SUDO_USER" -H "$REPO_ROOT/scripts/reconcile-ai-gateways.sh" || error "AI Gateway reconciliation failed during bootstrap."
else
    "$REPO_ROOT/scripts/reconcile-ai-gateways.sh" || error "AI Gateway reconciliation failed during bootstrap."
fi

# ------------------------------------------------------------
# Done
# ------------------------------------------------------------

echo
echo "============================================================"
echo " Bootstrap completed"
echo "============================================================"
echo
echo "Repository:"
echo "  $REPO_ROOT"
echo
echo "Machine:"
echo "  $MACHINE_DIR"
echo
echo "Hardware:"
echo "  $HARDWARE_CONFIG"
echo
echo "Configuration:"
echo "  $MACHINE_CONFIG"
echo
echo "You can now use:"
echo
echo "  ./scripts/build.sh"
echo
