-- ==============================================================================
-- Generator: Keymap Manifest -> Antigravity JSONC & Markdown Documentation
-- Run with: nvim -l scripts/generate-keymaps.lua
-- ==============================================================================

local script_path = debug.getinfo(1, "S").source:sub(2)
local repo_root = vim.fs.dirname(vim.fs.dirname(vim.fs.abspath(script_path)))
package.path = repo_root .. "/resources/nvim/lua/?.lua;" .. repo_root .. "/resources/nvim/lua/?/init.lua;" .. package.path

local manifest = require("keymaps.manifest")

-- 1. Validate manifest uniqueness
local seen = {}
for _, entry in ipairs(manifest.entries) do
  for _, m in ipairs(entry.modes) do
    local id = m .. ":" .. entry.key
    if seen[id] then
      io.stderr:write("Error: Duplicate keybinding in manifest: " .. id .. "\n")
      os.exit(1)
    end
    seen[id] = true
  end
end

-- 2. Generate Antigravity keybindings.generated.jsonc
local host_bindings = {}
table.insert(host_bindings, "// ==============================================================================")
table.insert(host_bindings, "// AUTO-GENERATED BY scripts/generate-keymaps.lua — DO NOT EDIT DIRECTLY")
table.insert(host_bindings, "// Generated from resources/nvim/lua/keymaps/manifest.lua")
table.insert(host_bindings, "// ==============================================================================")
table.insert(host_bindings, "[")

local first = true
for _, entry in ipairs(manifest.entries) do
  if entry.vscode and (entry.scope == "global_host" or entry.key:sub(1, 3) == "<C-") then
    -- Convert Vim key notation to VS Code key notation
    local vs_key = entry.key
      :gsub("<C%-(.-)>", "ctrl+%1")
      :gsub("<S%-(.-)>", "shift+%1")
      :gsub("<A%-(.-)>", "alt+%1")
      :gsub("<leader>", "space ")

    local item = string.format(
      '  %s{\n    "key": "%s",\n    "command": "%s",\n    "when": "editorTextFocus"\n  }',
      first and "" or ",\n",
      vs_key,
      entry.vscode
    )
    table.insert(host_bindings, item)
    first = false
  end
end
table.insert(host_bindings, "\n]")

local jsonc_content = table.concat(host_bindings, "\n") .. "\n"
local jsonc_path = repo_root .. "/resources/antigravity/User/keybindings.generated.jsonc"
vim.fn.mkdir(vim.fs.dirname(jsonc_path), "p")
local f_json = io.open(jsonc_path, "w")
if f_json then
  f_json:write(jsonc_content)
  f_json:close()
  print("✓ Generated: resources/antigravity/User/keybindings.generated.jsonc")
else
  io.stderr:write("Error: Could not write to " .. jsonc_path .. "\n")
  os.exit(1)
end

-- 3. Generate keymaps/generated-doc.md
local doc_lines = {
  "# Unified Keymap Reference",
  "",
  "> Auto-generated from `manifest.lua`. Single source of truth across Neovim, Neovide, and Antigravity IDE.",
  "",
  "| Modes | Key | Group | Description | Native Action | Antigravity Action |",
  "| :--- | :--- | :--- | :--- | :--- | :--- |",
}

for _, entry in ipairs(manifest.entries) do
  local modes = table.concat(entry.modes, ", ")
  local key = "`" .. entry.key:gsub("|", "\\|") .. "`"
  local group = entry.group or "general"
  local desc = entry.desc or ""
  local native = type(entry.native) == "string" and ("`" .. entry.native:gsub("|", "\\|") .. "`") or "function"
  local vscode = entry.vscode and ("`" .. entry.vscode:gsub("|", "\\|") .. "`") or "-"

  table.insert(
    doc_lines,
    string.format("| %s | %s | %s | %s | %s | %s |", modes, key, group, desc, native, vscode)
  )
end

local doc_content = table.concat(doc_lines, "\n") .. "\n"
local doc_path = repo_root .. "/resources/nvim/keymaps/generated-doc.md"
vim.fn.mkdir(vim.fs.dirname(doc_path), "p")
local f_doc = io.open(doc_path, "w")
if f_doc then
  f_doc:write(doc_content)
  f_doc:close()
  print("✓ Generated: resources/nvim/keymaps/generated-doc.md")
else
  io.stderr:write("Error: Could not write to " .. doc_path .. "\n")
  os.exit(1)
end

print("✓ All keymaps verified and generated successfully.")
