# ==============================================================================
# Umbriel Compositor Configuration
# Extends system default: /usr/share/umbriel/config.toml
# ==============================================================================

[include]
files = [
	"/usr/share/umbriel/config.toml",
	"keybinds.toml",
]

[general]
autostart = ["noctalia", "fcitx5 -d"]
mod_key = "super"
xwayland = true
show_cheatsheet = false
