# Vertical Candidate List
Vertical Candidate List=False
# Font
Font="JetBrainsMono Nerd Font 10"
# Menu Font
MenuFont="JetBrainsMono Nerd Font 10"
# Tray Font
TrayFont="JetBrainsMono Nerd Font 10"
Theme=noctalia
