# Lotus Per-App Configuration
# 0 = Off, 1 = Uinput (Smooth), 2 = Uinput (Slow), 3 = Uinput (Super Smooth), 4 = Surrounding Text, 5 = Preedit, 6 = Emoji Picker, 7 = Uinput (Select), 8 = Minecraft
slack=5
chrome=5
chromium=5
beekeeper-studio=5
google-chrome-stable=5
code=5
bks=5
com.microsoft.VSCode=5
google-chrome=5
code-oss=5
antigravity=5
lark=5
obsidian=5
discord=5
antigravity-ide=5
